development:
  server: "http://192.169.177.210:8001/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://192.169.177.210:8001/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
